version: 2
updates:
- package-ecosystem: composer
  directory: "/"
  schedule:
    interval: daily
    time: "03:00"
    timezone: "Europe/Helsinki"
  open-pull-requests-limit: 10
  labels:
    - "dependencies"
    - "php"
