version: "3.7"

services:

  mariadb:
    image: wodby/mariadb:10.4-3.8.1
    container_name: "${COMPOSE_PROJECT_NAME}-mariadb"
    stop_grace_period: 30s
    environment:
      MYSQL_ROOT_PASSWORD: password
      MYSQL_DATABASE: wordpress
      MYSQL_USER: wordpress
      MYSQL_PASSWORD: wordpress

  php:
    image: wodby/wordpress-php:7.3-dev-4.16.2
    container_name: "${COMPOSE_PROJECT_NAME}-php"
    environment:
      APP_ENV: dev
      WP_SITEURL: "https://${WP_HOSTNAME}"
      PHP_SENDMAIL_PATH: /usr/sbin/sendmail -t -i -S stonehenge-mailhog:1025
      DB_HOST: mariadb
      DB_USER: wordpress
      DB_PASSWORD: wordpress
      DB_NAME: wordpress
      PHP_FPM_USER: wodby
      PHP_FPM_GROUP: wodby
    ## Read instructions at https://wodby.com/docs/stacks/wordpress/local#xdebug
#      PHP_XDEBUG: 1
#      PHP_XDEBUG_DEFAULT_ENABLE: 1
#      PHP_XDEBUG_REMOTE_CONNECT_BACK: 0
#      PHP_IDE_CONFIG: serverName=my-ide
#      PHP_XDEBUG_IDEKEY: "my-ide"
#      PHP_XDEBUG_REMOTE_HOST: 172.17.0.1 # Linux
#      PHP_XDEBUG_REMOTE_HOST: 10.254.254.254 # macOS
#      PHP_XDEBUG_REMOTE_HOST: 10.0.75.1 # Windows
    volumes:
      - ./:/var/www/html:cached
    networks:
      - stonehenge-network
      - default

  nginx:
    image: wodby/nginx:1.17-5.8.13
    container_name: "${COMPOSE_PROJECT_NAME}-nginx"
    depends_on:
      - php
    environment:
      NGINX_STATIC_OPEN_FILE_CACHE: "off"
      NGINX_ERROR_LOG_LEVEL: debug
      NGINX_BACKEND_HOST: php
      NGINX_VHOST_PRESET: wordpress
      NGINX_SERVER_ROOT: /var/www/html/public
    volumes:
      - ./:/var/www/html:cached
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.${COMPOSE_PROJECT_NAME}-nginx.entrypoints=https"
      - "traefik.http.routers.${COMPOSE_PROJECT_NAME}-nginx.rule=Host(`${WP_HOSTNAME}`)"
      - "traefik.http.routers.${COMPOSE_PROJECT_NAME}-nginx.tls=true"
      - "traefik.http.services.${COMPOSE_PROJECT_NAME}-nginx.loadbalancer.server.port=80"
      - "traefik.docker.network=stonehenge-network"
    networks:
      - stonehenge-network
      - default

networks:
  stonehenge-network:
    external: true

volumes:
  ssh:
    name: stonehenge-ssh
    external: true
