pipeline:

  - name: Install dependencies
    type: command
    command: composer install -n --no-dev
    directory: $APP_ROOT

  - name: Copy wp-config.php
    type: command
    command: cp conf/wodby.wp-config.php public/wp-config.php
    directory: $APP_ROOT

  - name: Clean up installation
    type: command
    command: |
      wp --path=/var/www/html/public theme delete twentynineteen twentyseventeen && \
      wp --path=/var/www/html/public plugin delete akismet hello
    directory: $APP_ROOT

  - name: Make sure the files privileges are correct
    type: command
    command: chown -R www-data:www-data /var/www/html/public/wp-content/uploads
    directory: $APP_ROOT

  - name: Folder permissions for import module
    type: command
    command: mkdir -p -m 755 /var/www/html/public/wp-content/plugins/all-in-one-wp-migration/storage
    directory: $APP_ROOT
